version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v4"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v4"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v3"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v3"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v2"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v2"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
