package cluster

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
)

var _ = api.ServerEnvironment{}

var internalNonClusterMemberObjects = RegisterStmt(`
SELECT internal_non_cluster_members.id, internal_non_cluster_members.name, internal_non_cluster_members.address, internal_non_cluster_members.certificate
  FROM internal_non_cluster_members
  ORDER BY internal_non_cluster_members.name
`)

var internalNonClusterMemberObjectsByAddress = RegisterStmt(`
SELECT internal_non_cluster_members.id, internal_non_cluster_members.name, internal_non_cluster_members.address, internal_non_cluster_members.certificate
  FROM internal_non_cluster_members
  WHERE ( internal_non_cluster_members.address = ? )
  ORDER BY internal_non_cluster_members.name
`)

var internalNonClusterMemberObjectsByName = RegisterStmt(`
SELECT internal_non_cluster_members.id, internal_non_cluster_members.name, internal_non_cluster_members.address, internal_non_cluster_members.certificate
  FROM internal_non_cluster_members
  WHERE ( internal_non_cluster_members.name = ? )
  ORDER BY internal_non_cluster_members.name
`)

var internalNonClusterMemberID = RegisterStmt(`
SELECT internal_non_cluster_members.id FROM internal_non_cluster_members
  WHERE internal_non_cluster_members.name = ?
`)

var internalNonClusterMemberCreate = RegisterStmt(`
INSERT INTO internal_non_cluster_members (name, address, certificate)
  VALUES (?, ?, ?)
`)

var internalNonClusterMemberDeleteByAddress = RegisterStmt(`
DELETE FROM internal_non_cluster_members WHERE address = ?
`)

var internalNonClusterMemberUpdate = RegisterStmt(`
UPDATE internal_non_cluster_members
  SET name = ?, address = ?, certificate = ?
 WHERE id = ?
`)

// internalNonClusterMemberColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the InternalNonClusterMember entity.
func internalNonClusterMemberColumns() string {
	return "internal_non_cluster_members.id, internal_non_cluster_members.name, internal_non_cluster_members.address, internal_non_cluster_members.certificate"
}

// getInternalNonClusterMembers can be used to run handwritten sql.Stmts to return a slice of objects.
func getInternalNonClusterMembers(ctx context.Context, stmt *sql.Stmt, args ...any) ([]InternalNonClusterMember, error) {
	objects := make([]InternalNonClusterMember, 0)

	dest := func(scan func(dest ...any) error) error {
		i := InternalNonClusterMember{}
		err := scan(&i.ID, &i.Name, &i.Address, &i.Certificate)
		if err != nil {
			return err
		}

		objects = append(objects, i)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"internal_non_cluster_members\" table: %w", err)
	}

	return objects, nil
}

// getInternalNonClusterMembersRaw can be used to run handwritten query strings to return a slice of objects.
func getInternalNonClusterMembersRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]InternalNonClusterMember, error) {
	objects := make([]InternalNonClusterMember, 0)

	dest := func(scan func(dest ...any) error) error {
		i := InternalNonClusterMember{}
		err := scan(&i.ID, &i.Name, &i.Address, &i.Certificate)
		if err != nil {
			return err
		}

		objects = append(objects, i)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"internal_non_cluster_members\" table: %w", err)
	}

	return objects, nil
}

// GetInternalNonClusterMembers returns all available internal_non_cluster_members.
// generator: internal_non_cluster_member GetMany
func GetInternalNonClusterMembers(ctx context.Context, tx *sql.Tx, filters ...InternalNonClusterMemberFilter) ([]InternalNonClusterMember, error) {
	var err error

	// Result slice.
	objects := make([]InternalNonClusterMember, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = Stmt(tx, internalNonClusterMemberObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"internalNonClusterMemberObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Name != nil && filter.Address == nil {
			args = append(args, []any{filter.Name}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(tx, internalNonClusterMemberObjectsByName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"internalNonClusterMemberObjectsByName\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(internalNonClusterMemberObjectsByName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"internalNonClusterMemberObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Address != nil && filter.Name == nil {
			args = append(args, []any{filter.Address}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(tx, internalNonClusterMemberObjectsByAddress)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"internalNonClusterMemberObjectsByAddress\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(internalNonClusterMemberObjectsByAddress)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"internalNonClusterMemberObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Address == nil && filter.Name == nil {
			return nil, fmt.Errorf("Cannot filter on empty InternalNonClusterMemberFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getInternalNonClusterMembers(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getInternalNonClusterMembersRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"internal_non_cluster_members\" table: %w", err)
	}

	return objects, nil
}

// GetInternalNonClusterMember returns the internal_non_cluster_member with the given key.
// generator: internal_non_cluster_member GetOne
func GetInternalNonClusterMember(ctx context.Context, tx *sql.Tx, name string) (*InternalNonClusterMember, error) {
	filter := InternalNonClusterMemberFilter{}
	filter.Name = &name

	objects, err := GetInternalNonClusterMembers(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"internal_non_cluster_members\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "InternalNonClusterMember not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"internal_non_cluster_members\" entry matches")
	}
}

// GetInternalNonClusterMemberID return the ID of the internal_non_cluster_member with the given key.
// generator: internal_non_cluster_member ID
func GetInternalNonClusterMemberID(ctx context.Context, tx *sql.Tx, name string) (int64, error) {
	stmt, err := Stmt(tx, internalNonClusterMemberID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"internalNonClusterMemberID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "InternalNonClusterMember not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"internal_non_cluster_members\" ID: %w", err)
	}

	return id, nil
}

// InternalNonClusterMemberExists checks if a internal_non_cluster_member with the given key exists.
// generator: internal_non_cluster_member Exists
func InternalNonClusterMemberExists(ctx context.Context, tx *sql.Tx, name string) (bool, error) {
	_, err := GetInternalNonClusterMemberID(ctx, tx, name)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateInternalNonClusterMember adds a new internal_non_cluster_member to the database.
// generator: internal_non_cluster_member Create
func CreateInternalNonClusterMember(ctx context.Context, tx *sql.Tx, object InternalNonClusterMember) (int64, error) {
	// Check if a internal_non_cluster_member with the same key exists.
	exists, err := InternalNonClusterMemberExists(ctx, tx, object.Name)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"internal_non_cluster_members\" entry already exists")
	}

	args := make([]any, 3)

	// Populate the statement arguments.
	args[0] = object.Name
	args[1] = object.Address
	args[2] = object.Certificate

	// Prepared statement to use.
	stmt, err := Stmt(tx, internalNonClusterMemberCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"internalNonClusterMemberCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"internal_non_cluster_members\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"internal_non_cluster_members\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteInternalNonClusterMember deletes the internal_non_cluster_member matching the given key parameters.
// generator: internal_non_cluster_member DeleteOne-by-Address
func DeleteInternalNonClusterMember(ctx context.Context, tx *sql.Tx, address string) error {
	stmt, err := Stmt(tx, internalNonClusterMemberDeleteByAddress)
	if err != nil {
		return fmt.Errorf("Failed to get \"internalNonClusterMemberDeleteByAddress\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(address)
	if err != nil {
		return fmt.Errorf("Delete \"internal_non_cluster_members\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "InternalNonClusterMember not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d InternalNonClusterMember rows instead of 1", n)
	}

	return nil
}

// UpdateInternalNonClusterMember updates the internal_non_cluster_member matching the given key parameters.
// generator: internal_non_cluster_member Update
func UpdateInternalNonClusterMember(ctx context.Context, tx *sql.Tx, name string, object InternalNonClusterMember) error {
	id, err := GetInternalNonClusterMemberID(ctx, tx, name)
	if err != nil {
		return err
	}

	stmt, err := Stmt(tx, internalNonClusterMemberUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"internalNonClusterMemberUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Name, object.Address, object.Certificate, id)
	if err != nil {
		return fmt.Errorf("Update \"internal_non_cluster_members\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
